// packages/svelte/src/components/IncremarkHeading.svelte
<!--
  @file IncremarkHeading.svelte - 标题组件
  @description 渲染 Markdown 标题节点（h1-h6）
-->

<script lang="ts">
  import type { Heading } from 'mdast'
  import IncremarkInline from './IncremarkInline.svelte'

  /**
   * 组件 Props
   */
  interface Props {
    /** 标题节点 */
    node: Heading
  }

  let { node }: Props = $props()

  /**
   * 根据 depth 计算标签名
   * depth 范围：1-6，对应 h1-h6
   */
  const tag = $derived(`h${node.depth}`)

  /**
   * CSS 类名
   */
  const className = $derived(`incremark-heading incremark-heading--h${node.depth}`)
</script>

<svelte:element this={tag} class={className}>
  <IncremarkInline nodes={node.children} />
</svelte:element>

// packages/react/src/components/IncremarkHeading.tsx
import React from 'react'
import type { Heading, PhrasingContent } from 'mdast'
import { IncremarkInline } from './IncremarkInline'

export interface IncremarkHeadingProps {
  node: Heading
}

/**
 * Heading 组件
 *
 * 渲染 Markdown 标题（h1-h6）
 */
export const IncremarkHeading: React.FC<IncremarkHeadingProps> = ({ node }) => {
  const Tag = `h${node.depth}` as 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'

  return (
    <Tag className={`incremark-heading incremark-heading--h${node.depth}`}>
      <IncremarkInline nodes={node.children as PhrasingContent[]} />
    </Tag>
  )
}
