// packages/solid/src/components/IncremarkHeading.tsx
/* @jsxImportSource solid-js */

import type { Heading } from 'mdast'
import { Component } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import { IncremarkInline } from './IncremarkInline'

export interface IncremarkHeadingProps {
  node: Heading
}

export const IncremarkHeading: Component<IncremarkHeadingProps> = (props) => {
  const tag = () => `h${props.node.depth}`

  return (
    <Dynamic component={tag()} class={`incremark-heading incremark-heading--h${props.node.depth}`}>
      <IncremarkInline nodes={props.node.children} />
    </Dynamic>
  )
}

// packages/react/src/components/IncremarkHeading.tsx
import React from 'react'
import type { Heading, PhrasingContent } from 'mdast'
import { IncremarkInline } from './IncremarkInline'

export interface IncremarkHeadingProps {
  node: Heading
}

/**
 * Heading 组件
 *
 * 渲染 Markdown 标题（h1-h6）
 */
export const IncremarkHeading: React.FC<IncremarkHeadingProps> = ({ node }) => {
  const Tag = `h${node.depth}` as 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6'

  return (
    <Tag className={`incremark-heading incremark-heading--h${node.depth}`}>
      <IncremarkInline nodes={node.children as PhrasingContent[]} />
    </Tag>
  )
}
