// packages/vue/src/components/IncremarkHeading.vue
<script setup lang="ts">
import type { Heading } from 'mdast'
import { computed } from 'vue'
import IncremarkInline from './IncremarkInline.vue'

const props = defineProps<{
  node: Heading
}>()

const tag = computed(() => `h${props.node.depth}`)
</script>

<template>
  <component :is="tag" :class="`incremark-heading incremark-heading--h${node.depth}`">
    <IncremarkInline :nodes="node.children" />
  </component>
</template>

// packages/solid/src/components/IncremarkHeading.tsx
/* @jsxImportSource solid-js */

import type { Heading } from 'mdast'
import { Component } from 'solid-js'
import { Dynamic } from 'solid-js/web'
import { IncremarkInline } from './IncremarkInline'

export interface IncremarkHeadingProps {
  node: Heading
}

export const IncremarkHeading: Component<IncremarkHeadingProps> = (props) => {
  const tag = () => `h${props.node.depth}`

  return (
    <Dynamic component={tag()} class={`incremark-heading incremark-heading--h${props.node.depth}`}>
      <IncremarkInline nodes={props.node.children} />
    </Dynamic>
  )
}
